### PR TITLE
clear out unused in Auth0SyncService

### PR DESCRIPTION
**Pull request by makosblade**
This PR:
- gets rid of if-statement so that users are fully sync'd
- gets rid of unused variables/calls in syncUser

### CODE REVIEW

**Comment by you-leee** [comment]
Btw, isn't this a fix for this? https://jira.openlattice.com/browse/LATTICE-2333

**Comment by makosblade** [comment]
> Btw, isn't this a fix for this? https://jira.openlattice.com/browse/LATTICE-2333

yes!

**Comment by you-leee** [comment]
We should link them together

**Comment by you-leee** [comment]
If you include `LATTICE-2333` in the title, it should link them

**Comment by makosblade** [comment]
Yeah there used to be some slick integration between jira and github where you could create a branch in the appropriate repositories through jira and it would title it from the ticket number/title but I don't think we have it enabled/installed/configured

**Comment by you-leee** [comment]
It worked though :)

**Pull request merged**
