### PR TITLE
add API to delete a user

### PR DESCRIPTION
**Pull request by katherinebernstein**

### CODE REVIEW

**Comment by katherinebernstein** [comment]
> This is insufficient to properly delete a user. All permissions granted to the user should be cleared and the securable object principal corresponding to the user should be removed. In addition, the user should be removed from all organizations to which they belong.

All that should be covered in `HazelcastAuthorizationService.deletePrincipal`

**Comment by geekbeast** [comment]
> > This is insufficient to properly delete a user. All permissions granted to the user should be cleared and the securable object principal corresponding to the user should be removed. In addition, the user should be removed from all organizations to which they belong.
> 
> All that should be covered in `HazelcastAuthorizationService.deletePrincipal`

Is there a change I'm missing here? I don't see that function.

**Comment by geekbeast** [comment]
I see you are referring to HazelcastPrincipalService deletePrincipal not HazelcastAuthorizationService.  Okay looks good.

**Comment by katherinebernstein** [comment]
> I see you are referring to HazelcastPrincipalService deletePrincipal not HazelcastAuthorizationService. Okay looks good.

Oops yeah PrincipalService! Thanks!

**Pull request merged**
