### PR TITLE
clearEntities throws errors because it expects autoCommit to be off

### PR DESCRIPTION
**Pull request by katherinebernstein**

### CODE REVIEW

**Comment by makosblade** [comment]
Don't we definitely need to combine these into one query?
You could have a bit of a wait between the two queries depending on the scheduler

**Comment by katherinebernstein** [comment]
> Don't we definitely need to combine these into one query?
> You could have a bit of a wait between the two queries depending on the scheduler

Combine what into one query? This looks like it was just leftover from the locking code, but since locking was removed autoCommit will never be false here, so soft deletes are just always broken

**Comment by makosblade** [comment]
> > Don't we definitely need to combine these into one query?
> > You could have a bit of a wait between the two queries depending on the scheduler
> 
> Combine what into one query? This looks like it was just leftover from the locking code, but since locking was removed autoCommit will never be false here, so soft deletes are just always broken

The two Postgres queries should be combined because the thread running them can block in-between the queries resulting in potential badness/inconsistencies

**Comment by makosblade** [comment]
https://jira.openlattice.com/browse/LATTICE-2338

**Pull request merged**
