### PR TITLE
more commit

### PR DESCRIPTION
**Pull request by katherinebernstein**

### CODE REVIEW

**Comment by katherinebernstein** [comment]
Based on the bug @you-leee  found it seems like autocommit hadn't been set to false somewhere so I assume there's places where autocommit isn't set back to true after

**Comment by katherinebernstein** [comment]
If it's important that it's false and stays false we could update it more layers up though

**Comment by makosblade** [comment]
👍  Would be nice to have an annotation that can check such things at compile time :(

**Comment by katherinebernstein** [comment]
yeah :) or documentation :)

**Pull request merged**
